### ISSUE TITLE
Key of annotation property in `RouteLeg` object should be `annotation` instead of `annotations`

### ISSUE THREAD

**Issue by chungcf2006** [erikvullings/osrm-rest-client#1]
According to [OSRM API Documentation](http://project-osrm.org/docs/v5.22.0/api/#routeleg-object), the key of annotation property in `RouteLeg` object should be `annotation` instead of `annotations`.

**Comment by erikvullings** [comment]
@chungcf2006 Good catch, thanks! Releasing a fixed version...
